### ISSUE TITLE
Speed up new FontAwesomeNode( 'eye_close' )

### ISSUE THREAD

**Issue by samreid** [phetsims/function-builder#102]
I noticed that around 1000ms are being used (on 2012 macbook air) to call `new FontAwesomeNode( 'eye_close' )` in FunctionNode.js.  

To test this, I added this code in FunctionNode.js:

```js
      hiddenNode: (function(){
        var t = Date.now();
        var fontAwesomeNode = new FontAwesomeNode( 'eye_close' );
        var t2 = Date.now();
        window.sumTime=window.sumTime + (t2-t);
        return fontAwesomeNode;
      })(), // {Node} displayed when the function identity is hidden
```

Running a built version in chrome, I saw numbers like 800.  In firefox it was 1232.  In iPad, it is probably much worse.  It seems wasteful to parse the same SVG for so many milliseconds.  Perhaps the svg can be parsed once and reused using scenery DAG or perhaps there are better ideas.  Assigning to @pixelzoom for discussion, though I would understand if we unassign and decide not to work on this at the moment.

**Comment by pixelzoom** [comment]
@samreid's suggestion above is to make the client responsible for reusing instances of `FontAwesomeNode`. 

Other ideas, not mutually exclusive:

(1) Make `FontAwesomeNode` responsible for caching the `Shape` that's returned by private `getShapeByName`.  Downside is that once such a Shape is created, it will remain in memory regardless of whether it's being used.

(2) Make `getShapeByName` public, so that clients can cache the `Shape` if they wish, and use `Path` instead of `FontAwesomeNode`. 

(3) Get rid of `FontAwesomeNode`, and make it possible to `require` individual` icons, so that every sim that uses `FontAwesomeNode` doesn't have to pull in the full set of icons (private var `icons`).

**Comment by samreid** [comment]
We tried (1) with disastrous results:

```js
// At one point, shapes were cached to reduce the overhead of having to reinterpret the SVG each time the shape was
// loaded, but this led to memory leaks (see https://github.com/phetsims/joist/issues/329).  As a result, the icons
// are loaded anew each time.
```

(2) could help

(3) I don't expect that the static `var icons` code takes a long time to evaluate, because it is only done once per app and is just a handful of static strings.

**Comment by pixelzoom** [comment]
Looks to me like https://github.com/phetsims/joist/issues/329 was a result of poor implementation, not anything inherent in the idea of caching Shapes.  There are currently 16 icons provided by FontAwesomeNode, so (with caching) there would at most 16 cached Shapes.  Or am I missing something?...

**Comment by pixelzoom** [comment]
Is the goal of this issue to come up with an approach to solving this issue in general, or to solve it just for this sim?

**Comment by pixelzoom** [comment]
Is the goal of this issue to come up with an approach to solving this issue in general, or to solve it just for this sim? Because I can resolve this trivially for function-builder by simply creating one static FontAwesomeNode( 'eye_close' ) and using it everywhere.

**Comment by pixelzoom** [comment]
... I'll just need to be careful not to transform the `FontAwesomeNode` instance, and instead wrap it in a `Node` and transform the wrapper.

**Comment by pixelzoom** [comment]
A single instance of FontAwesomeNode is now reused, @samreid please review.

**Comment by pixelzoom** [comment]
Btw... I think that the approach I used (creating a Node subtype that has the static instance as its child) is a decent general approach.

**Comment by samreid** [comment]
> I think that the approach I used (creating a Node subtype that has the static instance as its child) is a decent general approach.

Yes, it looks great for static applications.  But if any of those node subtypes need to be garbage collected, they will explicitly need to detach their reference to the FontAwesomeNode or there will still be a path to a GC root.

**Comment by pixelzoom** [comment]
> ... But if any of those node subtypes need to be garbage collected...

I'll investigate this later in the week.

**Comment by samreid** [comment]
> ... But if any of those node subtypes need to be garbage collected...

I think in Function Builder objects are mainly static (all preallocated), so it may work here without a hassle.  But as for recommending that pattern for wider use, we would have to make sure to detach from the cached object on dispose.

**Comment by pixelzoom** [comment]
`FunctionNode` (line 46) creates an `EyeCloseNode` as the default value for options.hiddenNode, the node displayed when a function's identify is hidden.  `MysteryFunctionNode` (subtype of FunctionNode used for the "Mystery" screen) overrides options.hiddenNode with a `Text('?',...)`, see line 40.  So for every `MysteryFunctionNode` created (there are 24 of them) there will be an `EyeCloseNode` node that is created, but never added to the scene graph.

**Comment by pixelzoom** [comment]
In `FunctionNode`... Instead of creating an `EyeCloseNode` by default value for `options.hiddenNode`, I should probably set `hiddenNode: null`, then create an `EyeCloseNode` if the client doesn't set `options.hiddenNode`.

**Comment by pixelzoom** [comment]
`FunctionNode` changed in above commit so that it created an `EyeCloseNode` only if `options.hiddenNode` is not provided by the client.

**Comment by pixelzoom** [comment]
Since all instances of `FunctionNode` and its subtypes are created at startup and exist for the lifetime of the sim, I believe that there's no opportunity for memory leakage due to this optimization.

**Comment by pixelzoom** [comment]
@samreid anything else here?

**Comment by pixelzoom** [comment]
Ah... Thought of one more thing.  If this significantly affects startup time, then we might want to add it to a maintenance release in the 1.0 branch.   @samreid Is there a noticeable startup improvement on your MacBook Air?

**Comment by pixelzoom** [comment]
Thinking about this more...  I don't like the pattern I've used here.  There's no memory leak in function-builder only because it all instances of `FunctionNode` exist for the lifetime of the sim. And if that ever changes, instant memory leak.  I'll also need to address this in MOTHA, where I will be dynamically creating "trash buttons" for spectrometer snapshots that appear in a dialog.

Proposal:  Factor `FontAwesomeShape` out of `FontAwesomeNode`, so that clients can create these Shapes. FontAwesomeNode becomes a convenience Node.  For situations where performance is not an issue, clients can use FontAwesomeNode.  For other situations, clients can create and manage one instance of a FontAwesomeShape for each icon needed, and create their own Path nodes to render those Shapes.

**Comment by pixelzoom** [comment]
@samreid and I discussed this issue (in general and specific to function-builder) via Skype.  The preferred solution is to: (1) give clients access to creating of Shapes for fontawesome icons, and (2) address caching in FontAwesomeNode, and (3) prevent memory leaks by telling Path that it's provided Shape is static and should not be observed for changes.  See https://github.com/phetsims/function-builder/issues/102 for specific recommendations. When that issue is resolved, function-builder should be modified to use the new approach.

**Comment by samreid** [comment]
I'd like to be able to publish a PhET-iO version for data recording before Thursday, is this stable for release out of master?  If not, when will a good time be?

**Comment by pixelzoom** [comment]
Depends on when https://github.com/phetsims/sun/issues/270 is addressed, it's a prerequisite for addressing this issue correctly.  What's currently checked in is probably superior to what was published in 1.0.0, but has not been thoroughly tested.

**Comment by pixelzoom** [comment]
Shape caching is being added in https://github.com/phetsims/sun/issues/270, so I've changed the implementation here in anticipation of that feature. Until that issue is completed (which involves adding the ability to make Shapes immutable), function-builder will be leaking memory via the Shape cache.

**Comment by pixelzoom** [comment]
Prerequisite for https://github.com/phetsims/phet-io/issues/642, which must be completed by 9/29.  Raising priority to high.

**Comment by samreid** [comment]
> function-builder will be leaking memory via the Shape cache.

I'm not opposed to fixing this, but trying to understand the problem better.  Function Builder never needs to remove something from the cache, so there is not a memory leak in its case, right?

**Comment by pixelzoom** [comment]
Until `Shape.makeImmutable` is implemented, all FontAwesomeNodes are leaking because the Shapes in the cache have references to them.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/sun/issues/270#issuecomment-249673373, `Shape.makeImmutable` was implemented and integrated into `FontAwesomeNode`.   When that issue has been verified, this issue can be closed.

**Comment by samreid** [comment]
I'm on the hook for the review in https://github.com/phetsims/sun/issues/270#issuecomment-249673373, so I'll assign this issue to myself as well.

**Comment by samreid** [comment]
On hold as described in the preceding comment.

**Comment by samreid** [comment]
OK I verified the issue in https://github.com/phetsims/function-builder/issues/102#issuecomment-249698002 so this can be closed.  I also counted the time to create the eye close icons in this new version by changing EyeCloseNode to be:

```js
  var tot = 0;
  /**
   * @param {Object} [options]
   * @constructor
   */
  function EyeCloseNode( options ) {
    var t1 = Date.now();
    FontAwesomeNode.call( this, 'eye_close', options );
    var t2 = Date.now();
    tot+=(t2-t1);
    console.log(tot);
  }
```
and it is down to 59ms, which is much better!  Thanks, closing.
