### ISSUE TITLE
[1.1.3-rc.1-phetio] Recorder Wrapper Doesn't work.

### ISSUE THREAD

**Issue by JRomero0613** [phetsims/function-builder#119]
Test Device: PC Laptop

OS: Windows 10 v. 1803

Google Chrome v. 67.0.3396.87

Problem Description: For phetsims/QA#128 when running this sim version with the recorder wrapper nothing comes up on the screen and the console gives the following error:

```

Uncaught TypeError: QueryStringMachine.containsKey is not a function
    at Object.launchSim (SimIFrameClient.js:281)
    at record.js:25
    at window.Recorder.start (Recorder.js:121)
    at record.js:24
    at record.js:32

```

**Comment by JRomero0613** [comment]
I have tried this with the &phet-io.emitInputEvents query parameter and the recording wrapper still does not work. I do get a different error from the one previously with this new query parameter:

```

QueryStringMachine.js:4 Uncaught Error: Assertion failed: illegal value for boolean: undefined
    at d (QueryStringMachine.js:4)
    at i (QueryStringMachine.js:4)
    at o (QueryStringMachine.js:4)
    at Object.getForString (QueryStringMachine.js:4)
    at Object.get (QueryStringMachine.js:4)
    at record.js:17
    at record.js:32

```

**Comment by zepumph** [comment]
because that is a boolean query parameter, try `&phet-io.emitInputEvents=true`

**Comment by JRomero0613** [comment]
I am still not able to run the recorder wrapper using this new query parameter or any of the other ones used before. I get the same error as before seen in https://github.com/phetsims/function-builder/issues/119#issuecomment-397750826

**Comment by pixelzoom** [comment]
Is this issue specific to Function Builder, or something general?

Is there some PhET-iO activity going on for Function Builder that I'm not aware of?

**Comment by zepumph** [comment]
@pixelzoom this is a maintenance release for a version from last October or so.

@JRomero0613 I apologize! I got confused on issues. I too am getting that weird error about query string machine. I'm unsure what that is about. I'll look into it.

**Comment by zepumph** [comment]
When looking at the diff between that branch and when it was on master, https://github.com/phetsims/function-builder/compare/1.1-phetio, it looks like 1.1.0 and 1.1.1 were both delivered, but there are commits, and updated dependency commits for a 1.1.2 from Nov 12, 2016. This is strange because there isn't a 1.1.2 release on phet-io production. Then I found the paper trail for 1.1.2 starting here https://github.com/phetsims/phet-io/issues/654#issuecomment-260157881
It looks like 1.1.2 was only a dev release, and for the playback wrapper. It seems like when the phet-io repo was updated (and sherpa), it broke the record wrapper, but fixed the playback wrapper. I'm going to revert the changes made for 1.1.2 so that the new version will have a working recording wrapper with the scenery fix.

Taggin @samreid so he is aware of what I will do.

**Comment by JRomero0613** [comment]
@zepumph When you make those changes to the new version let me know and I can test it for you

**Comment by zepumph** [comment]
I don't know how to proceed. I tried deploying this simulation with chipper 1.0 and 2.0, and can't deploy it. I successfully was able to revert the shas I wanted to, so the tip of the branch is ready for a new RC. @jonathanolson how did you deploy the previous rc. 

When trying to use chipper 2.0, I wasn't able to build it successfully because the old chipper needed to see the "phetio" string in the version, so either that failed, or, if I added that string, chipper 2.0 couldn't properly increment the version.

When trying to use chipper 1.0, it sent off the build request as expected, but that build failed with:
```
Build failure: Build aborted,Error: ENOENT: no such file or directory, open '../function-builder/build/wrappers/.htaccess'. Sim = function-builder Version = 1.1.3-phetiorc.2 Locales = * Shas = {"comment":"# function-builder 1.1.3-phetiorc.2 Thu Jun 28 2018 12:20:37 GMT-0800 (Alaskan Daylight Time)","assert":{"sha":"845be6b591cb746b0b05b7023208aef2e49a8855","branch":"HEAD"},"axon":{"sha":"b24819252905c5eb1506f77f914ac6eb2426d028","branch":"HEAD"},"brand":{"sha":"880a18ded11185580cf5950e568931cf0df4eb87","branch":"HEAD"},"chipper":{"sha":"5f52de352ec59ab1a6fe91608908e9aaedb8041f","branch":"HEAD"},"dot":{"sha":"993d48e69cb042b20a981d1be885d463d731519c","branch":"HEAD"},"function-builder":{"sha":"3cfa22109681c5c8d1b91b50fd8037fbacb665be","branch":"1.1-phetio"},"joist":{"sha":"96c109c6d6d9528fee2b2b2cbd6a6d6033bf3fe8","branch":"HEAD"},"kite":{"sha":"55b5ee47e9df1ebf94e4d0c3e29e15d752b9ff83","branch":"HEAD"},"phet-core":{"sha":"ee1f025a440712ca11a42a05d6c46e9609d2e1b3","branch":"HEAD"},"phet-io":{"sha":"d2293c3ed7449424f87494276527d28ee010d560","branch":"HEAD"},"phetcommon":{"sha":"5a539ab931b94a3f65ba9c01fbe121c9c1f0774b","branch":"HEAD"},"query-string-machine":{"sha":"0bf0c1aac5e9de525cc9043167e4eaf366512b0e","branch":"HEAD"},"scenery":{"sha":"fe1116ef934c3b7b417d3ee3381e20c2d00439e9","branch":"HEAD"},"scenery-phet":{"sha":"d471774a5f5656311a073350fbf0b9149eb5af79","branch":"HEAD"},"sherpa":{"sha":"785d9664b4f30291119b8021498c788a47318b9f","branch":"HEAD"},"sun":{"sha":"58f6612d1ab0fbf1b322f49ca318103b86db8ef9","branch":"HEAD"},"tandem":{"sha":"fa89ce899f84a0cddb81971e7ae739773706721a","branch":"HEAD"},"twixt":{"sha":"53b54ee245977e1c86d69c011e00c0f0ffd4b7fd","branch":"HEAD"}}

```

**Comment by jonathanolson** [comment]
I'm going to move forward to see if I can do an RC deploy off of the 1.1-phetio branch.

**Comment by jonathanolson** [comment]
Ahh yup, as noted it is failing with:
```
Fatal error: Aborted rc deployment since the version number cannot be incremented safely (testType:phetiorc)
```

**Comment by zepumph** [comment]
Yes please do! I committed that to try to use chipper 1.0 to deploy. I don't care how it's deployed though.

**Comment by jonathanolson** [comment]
Failure with:
```
Warning: phet-io branded things must have phetio in the string so they will be properly dealt with on build-server Use --force to continue.
```

@mattpen presumably it's fine to patch whatever version of chipper it's using to not fail for this, since our deployment will be run with the proper brand, correct?

**Comment by mattpen** [comment]
This is fine if we are using chipper 2.0.  For chipper 1.0, phetio must be in the string or we will have to make changes to the build-server.

**Comment by jonathanolson** [comment]
Patched and deployed to https://phet-dev.colorado.edu/html/function-builder/1.1.3-rc.5.

**Comment by jonathanolson** [comment]
Hmm, a build order was reported, one sec.

**Comment by jonathanolson** [comment]
@mattpen can you look into this failure?

```
Build failure: Build aborted,Error: ENOENT: no such file or directory, open '../function-builder/build/wrappers/.htaccess'. Sim = function-builder Version = 1.1.3-rc.5 
```

**Comment by zepumph** [comment]
@mattpen this may have to do with the update to use `writePhetioHtaccess` that we did recently. I think that we will still need to support chipper 1.0 for phet-io in this way though.

**Comment by jonathanolson** [comment]
Also had a fail for the first normal phet-io maintenance release:
```
Build failure: Build aborted,Error: rsync exited with code 23. Sim = balloons-and-static-electricity
```

**Comment by mattpen** [comment]
> Build failure: Build aborted,Error: ENOENT: no such file or directory, open '../function-builder/build/wrappers/.htaccess'. Sim = function-builder Version = 1.1.3-rc.5 

@zepumph @jonathanolson - This error is because the build-server assumes that the .htaccess file should belong in `{{sim-name}}/build/wrappers` (chipper 1.0) or `{{sim-name}}/build/{{brand}}/wrappers` (chipper 2.0).  In the case of this sim, the appropriate directory for the .htaccess file is actually `{{sim-name}}/build/protected`.  We can either add some logic to the build-server so that it can determine when it is building a sim with this directory structure.  This raises the question of whether there are other directory structures that we haven't considered yet due to their age.  I'm thinking it might be easier to update the sims dependencies to use the more modern version of the wrappers directory since we are already doing a maintenance release.   Thoughts?

**Comment by mattpen** [comment]
> Build failure: Build aborted,Error: rsync exited with code 23. Sim = balloons-and-static-electricity

All files appear to have been transferred successfully, but the command fails to update the time on the target directories.  It looks like this may be due to rsyncing to or from an NFS (https://stackoverflow.com/a/668049/2496827).  I'm going to add the `--omit-dir-times` flag which should resolve this.

**Comment by pixelzoom** [comment]
7/12/18 dev meeting:
• FB only has "phet-io lite" and was provided for research studies. So we don't need to patch this release branch of FB.  No one should try to patch this, so it's OK if it fails. 
• @jonathanolson will remove FB from phet-io-maintenance.json.

**Comment by samreid** [comment]
@kathy-phet FYI if you know of research partners that will need to use Function Builder for scenery input event playback, we should publish a new version from master.
