### ISSUE TITLE
Usability on small screens review

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/function-builder#125]
Per @kathy-phet's request in https://github.com/phetsims/QA/issues/295 I am making issues in each published sim repo detailing the pointer areas and usability of sims on phone sized screens.  Done on an iPhone 7 iOS 12 device.

Potential Difficulties Noticed:
* Carousel dots can't be interacted with
* Pointer areas visible when something is in a different part of the carousel (screen 4)

Screenshots:
![Image from iOS (1)](https://user-images.githubusercontent.com/41024075/56166650-6de3fd00-5f93-11e9-908c-fc378c9ed7e0.png)
![Image from iOS (2)](https://user-images.githubusercontent.com/41024075/56166651-6de3fd00-5f93-11e9-964c-dd9ebd7b176f.png)
![Image from iOS (3)](https://user-images.githubusercontent.com/41024075/56166652-6de3fd00-5f93-11e9-90dc-93e793de5048.png)
![Image from iOS (4)](https://user-images.githubusercontent.com/41024075/56166653-6de3fd00-5f93-11e9-8e3c-496a12f526ef.png)
![Image from iOS (5)](https://user-images.githubusercontent.com/41024075/56166654-6de3fd00-5f93-11e9-9a3b-e459473b9edc.png)
![Image from iOS](https://user-images.githubusercontent.com/41024075/56166655-6de3fd00-5f93-11e9-9cbc-bf8fec2a79b3.png)

**Comment by pixelzoom** [comment]
@KatieWoe said:
> * Pointer areas visible when something is in a different part of the carousel (screen 4)

Can you clarify?   I'm looking at the screenshot that you provided for screen 4 (Mystery) and I don't see the problem.

**Comment by pixelzoom** [comment]
@KatieWoe you didn't mention it, but this is also a general problem:

![screenshot_963](https://user-images.githubusercontent.com/3046552/56167161-a506de00-5f94-11e9-8180-1672dfccb381.png)

The drawer's control overlaps with the middle piece in the functions carousel.

**Comment by KatieWoe** [comment]
Sorry, I miscounted.  I meant third screen.  If you look to the right of the bottom carousel.  In addition, when the x/y table isn't extended the pointer areas of their up/down buttons are still visible.  Neither are intractable though.  Good catch with https://github.com/phetsims/function-builder/issues/125#issuecomment-483429139.

**Comment by pixelzoom** [comment]
Re pointer areas for things that are outside the clipping area of the carousel...  It's caused by the fact the scenery does not consider clipping when drawing pointer areas.  So you'll see pointer areas for things that are not drawn and can't possibly be interacted with. We previously decided that this was a non-issue, see https://github.com/phetsims/function-builder/issues/81#issuecomment-230060282.  So my recommendation is to do nothing.

Re page control ("dots") for the carousel... There's nothing we can really do here. And I don't think this control needs to be usable on small screens.  Again, my recommendation is to do nothing.

Re draw handle...  Our only option here is to reduce the height of the touchArea. It looks extreme anyway, so I recommend adjusting uniformly for all drawers in the sim.   I've reduced from 25 to 8, see screenshot below.  @KatieWoe please verify that this feels usable on small screens. @arouinfar please review.

![screenshot_964](https://user-images.githubusercontent.com/3046552/56167890-b2bd6300-5f96-11e9-9f83-88f3292bbece.png)

**Comment by KatieWoe** [comment]
@pixelzoom Still perfectly usable on the small screen in master.

**Comment by pixelzoom** [comment]
@amanda-phet over to approve the decisions in https://github.com/phetsims/function-builder/issues/125#issuecomment-483433394 and close.

**Comment by amanda-phet** [comment]
>Our only option here is to reduce the height of the touchArea. It looks extreme anyway, so I recommend adjusting uniformly for all drawers in the sim. I've reduced from 25 to 8, see screenshot below. @KatieWoe please verify that this feels usable on small screens. @amanda-phet please review.

I think this change look good. I agree that the others can be left as-is.
