### ISSUE TITLE
revisit artwork on functions and cards

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#13]
From 1/28/16 meeting notes in the design document:

![screenshot_22](https://cloud.githubusercontent.com/assets/3046552/13782738/fb05a48c-ea8d-11e5-9d73-ebb198d7ab57.png)

**Comment by pixelzoom** [comment]
I don't think we want to change the background color of the cards; white is key to the clarity of the image functions.  So we'll probably need to fiddle with the background color of the carousels (and consequently their scroll button colors).

Here's a quick comparison between 2 extremes, using the "single" scene on the "Patterns" screen. 

Current card carousels where both the cards and carousels have white backgrounds:

![screenshot_24](https://cloud.githubusercontent.com/assets/3046552/13783686/eaf205d2-ea91-11e5-8451-2ee6ce8789a4.png)

The same scenarios with black carousel background:

![screenshot_23](https://cloud.githubusercontent.com/assets/3046552/13783716/11043f1a-ea92-11e5-88db-94be58e3f9c6.png)
 
I'm not advocating changing to black, just showing the extremes.

**Comment by pixelzoom** [comment]
Going back to EM's original observations... The images were difficult to see on white cards, which may or may not be affected by the background of the carousels.  So we should also investigate increasing the contrast of the artwork.

**Comment by pixelzoom** [comment]
I'd also be interested to know the context of these observations. How many students? Was their an impairment involved? etc.

**Comment by ariel-phet** [comment]
@pixelzoom the observation was just EM sitting in the back of the room and viewing on the projector, no students involved

**Comment by pixelzoom** [comment]
Note that if we make the images crisper, then we will undoubtedly notice degradations in image quality due to image processing and browser deficiencies. And the latter cannot be addressed by using mipmap in this sim, due to the image processing requirements.

**Comment by pixelzoom** [comment]
3/17/16 status meeting: 
@emily-phet also suggested to reduce the amount of detail in the images.

**Comment by emily-phet** [comment]
After seeing more of the representations being included in this sim today in status, I think in addition to attending to contrast (e.g., darkening colors and/or adding outline stroke to reps like the snowflake) you might consider increasing the size of the representations on the cards (there's a lot of padding) and decreasing the level of detail. I looked around online for some iconic, very low detail, variations of representations that give an idea of what I'm imagining:

Camera:
<img width="358" alt="screen shot 2016-03-17 at 10 47 24 am" src="https://cloud.githubusercontent.com/assets/5109055/13853737/b4b6b1be-ec2d-11e5-973e-5500b9aba31c.png">

Ferris Wheel:
<img width="511" alt="screen shot 2016-03-17 at 10 54 27 am" src="https://cloud.githubusercontent.com/assets/5109055/13853929/a429698a-ec2e-11e5-8c5f-d119a2dec6aa.png">

My main concern is that I believe the idea behind the representations on the cards is for each representation to be immediately identifiable, so the teacher/student can focus on the actions of the function(s) on the card. Right now, I think some of the representations require a pause to make out what they are, either because of low color contrast (e.g., snowflake), or because of the high level of detail (e.g., camera). I don't think you want the users to be pausing to think "what's that......oh, it's a snowflake!" while they're using the sim. I think you want users thinking "sun, cherries, snowflake...what do I want to do with these?".

Similarly, some of the more abstract outcomes of the function may be more difficult to recognize because of the contrast/detail issue, e.g, the Warhol effect was hard for me to recognize in status. My first thought was "oh, the soup can results in a brightly colored card." This seemed odd to me, so after further looking/thinking I realized the soup can results in a four tiled Warhol-like image but this was not immediately obvious.

**Comment by pixelzoom** [comment]
There's a little terminology issue that seems to be causing some confusion here. "Cards" are the things in the left and right vertical carousels.  "Functions" are the things in the bottom-center horizontal carousel.  To address @emily-phet's concerns, it sounds like we need to revisit the artwork for both cards and functions.  I've change the title of this issue to reflect that.

**Comment by pixelzoom** [comment]
Since @amanda-phet is on leave, assigning to @ariel-phet to decide how to get going on this.

**Comment by ariel-phet** [comment]
Deferring until after we have more functionality in the sim

**Comment by pixelzoom** [comment]
The Patterns screen is now fully functional, and we're 7 weeks out from RC testing.  Recommend to assign this to someone to address, interview on revised icons, and iterate.

**Comment by pixelzoom** [comment]
The asset file for the function and card icons is in GitHub at https://github.com/phetsims/function-builder/blob/master/assets/function-and-card-icons.ai. Please use this file as a starting point for revising the icons, and send me the revised .ai file.

**Comment by pixelzoom** [comment]
Looks like it could be related to clipArea, undoubtedly a scenery issue, but no idea how to address this. 

Assigning to @ariel-phet to prioritize and assign.

Mentioning @jonathanolson since he will undoubtedly be involved.

**Comment by ariel-phet** [comment]
Discussed with @amyh-phet today and worked on some changes. It seems like a few relatively minor tweaks could address the problem spots

**Comment by pixelzoom** [comment]
Email from @amyh-phet on 5/16/16:

> Attached is the revised artwork for the cards and functions for Function Builder. Changes were made to the following artwork:

Card icons:
-footprints 
-snowflake
-rectangle
-star

Function icons:
-rotate 90
-rotate 180

I've also included a png file for the star.  Not sure if it is helpful - artboard was set to 123 x 123 so the star should be centered and rotate properly.

**Comment by pixelzoom** [comment]
Assigning to me to integrate the revised artwork that was provided.

**Comment by pixelzoom** [comment]
The new icons are in this dev version:
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.29/function-builder_en.html

@amyh-phet and @ariel-phet, please review.

**Comment by emily-phet** [comment]
@pixelzoom: These icons definitely look "bolder" on my laptop than the previous ones. It would be great to be able to see them projected tomorrow in status, if possible.

**Comment by ariel-phet** [comment]
@pixelzoom I think overall these look good. I felt like the arrow on the rotate90 and rotate180 could be a bit thicker, so I went ahead and made that change and re-uploaded the .ai file to github. See what you think.

The one other tweak I would make is to make the B/W camera a bit larger. It looks to me as it could fill up a bit more space on the card and not cause a problem

![capture](https://cloud.githubusercontent.com/assets/4051174/15360273/2f287a82-1cca-11e6-92e8-c45c062d87b7.PNG)

**Comment by ariel-phet** [comment]
Maybe 10-15% larger for the camera

**Comment by pixelzoom** [comment]
Changes committed:

• Grayscale (camera) icon is now 15% larger
• Large arrows on Rotate90 and Rotate180

I also made an additional subtle change to Rotate90 and Rotate180.  Previously these looked like this:

![screenshot_32](https://cloud.githubusercontent.com/assets/3046552/15367006/48c32784-1ce4-11e6-9a9c-19248252112e.png)

Now they look like this:

![screenshot_33](https://cloud.githubusercontent.com/assets/3046552/15367013/4f8883b6-1ce4-11e6-9e67-4b996f2c1785.png)

In addition to the thicker arrow, I used the arrow fill color for the ferris wheel "seats" at the ends of the arrows.

**Comment by pixelzoom** [comment]
Reviewed with @ariel-phet via Skype, looks good.

Remaining work: Look at this on projector at status meeting.

**Comment by amanda-phet** [comment]
These changes look good to me. And thank you Chris for making the recent change to the ferris wheel. The original chair colors were subtle clues about the rotation so I like that you preserved that. Otherwise I was going to suggest that the arrow doesn't need to remain purple.

Get Outlook for Android<https://aka.ms/ghei36>



On Wed, May 18, 2016 at 9:41 AM -0700, "Chris Malley" <notifications@github.com<mailto:notifications@github.com>> wrote:


Reviewed with @ariel-phet<https://github.com/ariel-phet> via Skype, looks good.

Remaining work: Look at this on projector at status meeting.

-

**Comment by ariel-phet** [comment]
Reviewed at status meeting 5/19/2016, all looks good projected. Closing.
