### ISSUE TITLE
InvalidStateError on startup

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#15]
Reported by @ariel-phet with 1.0.0-dev.13 on Win7 with FF 45. 
Reproduced by @pixelzoom on Mac OS X 10.11.3 with FF 44.0.2.

To reproduce (sporadically, not consistently):

1. Clear your FF cache (Preferences -> Advanced -> Network -> “Clear Now” buttons (2)
2. Open the console (Tools -> Web Developer -> Toggle Tools)
3. Run the sim: http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.13/function-builder_en.html
4. You'll see this error in the console:

`InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable`

**Comment by pixelzoom** [comment]
I suspect that this may be related to an image (or canvas?) not being ready for use.  Images on the cards are read using the image plug-in. In `ImageCard.withImage` the image is written to a canvas using `CanvasUtils.createCanvasWithImage`.  The canvas is display in using a scenery.Image, see `ImageCardNode.updateContent`. No image functions are applied at startup, so we can safely ignore the image-processing code (which is canvas-based).

@jonathanolson Do you have any thoughts/hints on this?

**Comment by jonathanolson** [comment]
For what it's worth, I just can't seem to reproduce this on a freshly-built version from master, even though I can reliably reproduce with the given link. I'll need to reproduce (ideally on a build without uglification) to speed up tracking this down.

This leads me to suspect it's actually a problem when it is drawn BACK to a Canvas. I checked phet.joist.display.popupDebug(), and 1.1.0-dev.13 from an initial glance had Canvas elements, while master seemed not to (SVG). Could present (potentially) in Edge also due to this.

SVG code just accesses the URL, so it should be safe with data URIs (it reads the URL off of image.src and uses it in the SVG element).

I've added https://github.com/phetsims/scenery/issues/536 for the Canvas change (if the image isn't ready, do NOT call drawImage). Since the image loading will mark the image as 'dirty', it should force an update when the image HAS loaded.

The downside to this would be a potential 1+ frame delay where the image is not displayed. One option would be to use ```new Image( canvas )``` if the Image is being displayed in Canvas (i.e. Edge, older versions like 1.0.0-dev.13), and ```new Image( canvas.toDataURL() )``` if the Image is being displayed in SVG. It's messy, but should force things to have higher graphics quality when available (I saw #4), and still immediately render the images.

@pixelzoom, any further thoughts about better ways of working around this, and whether a 1+ frame delay would be unacceptable?

**Comment by pixelzoom** [comment]
If the 1+ frame delay results in a "noticeable" absence of the image, then likely not acceptable. And of course "noticeable" will likely vary from sim to sim.

I unfortunately don't have any suggestions for a better workaround. I don't have much understanding of scenery internals, which seems to be required in this case.

Also no idea what you can't reproduce this on a freshly-built version from master. I did make some changes today, but nothing related to how the images are rendered or processed.

So (if you have time) please proceed with debugging, let me know what you come up with. @ariel-phet please provide guidance on the priority of this issue.  Since this is fundamental to the image processing in Function Builder, I'd have it's relatively high priority.

**Comment by ariel-phet** [comment]
@jonathanolson I would agree considering the centrality of function builder to the math grant, this would be go to investigate sooner than later. Marking as high priority.

**Comment by jonathanolson** [comment]
This was actually caused by screen constructors being called before the images were loaded (i.e. before the SimLauncher.launch callback was called). Applied fix in master as noted above (as it's probably generally the correct thing to do), even though I haven't been able to reproduce in master.

With caches cleared, the starImage used for the pattern screen would have width/height 0, and trying to Warhol it (drawing 0x0 into a 0x0) seems to have caused the Firefox issue.

Since I can't reproduce any issues in master (even with rootRenderer=canvas), I'd lean towards closing this issue, and handling https://github.com/phetsims/scenery/issues/536 independently.

@pixelzoom, should this be tagged for developer-meeting to discuss whether we should construct screens after images are loaded?

**Comment by pixelzoom** [comment]
Thanks @jonathanolson.  

Searching for "var screens =", I see 16 other sims that are creating screens before `SimLauncher.launch` is called. (Possibly more, if they are using a different var name.) Do you recommend that we change those sims?

**Comment by pixelzoom** [comment]
Tagged for developer meeting to make other devs aware of this general issue, and decide what to do about other sims that are creating screens before calling `SimLauncher.launch`.

**Comment by pixelzoom** [comment]
For all of the sims that I'm responsible for, I moved instantiation of screens into the callback provide to SimLauncher.launch. The general pattern is:

```js
SimLauncher.launch( function() {
    var screens = [ ... ];
    var sim = new Sim( titleString, screens, options );
    sim.start();
  } );
```

Remaining sims that should consider doing this (identified by searching for `var screens =`, so there may be others):

capacitor-lab-basics @jessegreenberg 
chains @samreid 
fraction-comparison ??
rutherford-scattering @phetsims/schmitzware 
seasons ??
unit-rates @phetsims/schmitzware

**Comment by jessegreenberg** [comment]
Sounds good, did this for capacitor-lab-basics.  Also looked through other sims that I have worked on to verify that screens are instantiated inside of SimLauncher.launch.

**Comment by samreid** [comment]
I manually looked at all 80 occurrences of `new Sim` and identified the cases that were not instantiating screens in the launch callback, fixed the 7 occurrences I found (including but not limited to the ones @pixelzoom pointed out above), tested each in requirejs mode and committed.  @pixelzoom want to review anything?

**Comment by pixelzoom** [comment]
I feel no need to review. Closing.
