### ISSUE TITLE
[iOS] performance while updating outputs

### ISSUE THREAD

**Issue by phet-steele** [phetsims/function-builder#36]
@pixelzoom iPad performance issue for phetsims/tasks/issues/589. Testing on Tycho (iPad 2 iOS 9.3.1).

The iPad 2 momentarily struggles when updating outputs in the output carousel. To see what I mean:

1. Select the multi-slot function machine on the Patterns screen.
2. Populate the outputs fully, use `?populateOutputs` if you so desire.
3. Put some functions into the function machine so the sim has to update all outputs at once. I like to use Warhol and Mystery C functions, there will be a pretty noticeable pause when using these functions. This works especially well when utilizing all 3 slots.

**Comment by pixelzoom** [comment]
Presumably this is only an issue in the Patterns screen, since the math-related functions are trivial compared to image processing.

The most expensive imaging processing configuration is MysteryC + Warhol + Warhol. I'm testing on my iPad2 with iOS 9.3.1. 

Test1: With MysteryC + Warhol + Warhol and 1 instance of each card, there is a slight pause when adding/removing one of the functions from the builder, but it doesn't seem unacceptable, and doesn't feel like it's affecting usability. 

Test2: Same as Test1, but with *2* instances of each card in the output carousel. Here the performance starts to feel like it's affecting usability.  If this is a concern, then we should first revisit why we have 2 instances of each card in the Patterns screen.

Assigning to @ariel-phet to:
(1) confirm that performance of Test1 is acceptable
(2) determine whether performance of Test2 is a concern, and if so
(3) determine whether we need 2 instances of each card in the Patterns screen

**Comment by phet-steele** [comment]
> Presumably this is only an issue in the Patterns screen, since the math-related functions are trivial compared to image processing.

@pixelzoom yes, correct. Forgot I was planning on mentioning that in the original post.

**Comment by pixelzoom** [comment]
Options for addressing image-processing performance, not necessarily mutually exclusive:

(1) One instance of each card instead of 2, as mentioned above.
(2) Drop the Warhol function (would be a shame, since so much work has gone into it)
(3) Look at other ways to implement Warhol that might be more performant (will further increase the cost of Warhol)
(4) Replace MysteryC with a less expensive function
(5) Don't worry about it, and assume if the user puts every card in the output carousel, then it's OK if usability is impacted.

**Comment by ariel-phet** [comment]
Discussed with @pixelzoom over skype. Agreed on Test 1, minimal impact on user experience.

For Test 2, agreed, that performance is clearly affecting user experience, but some caveats:
- requires all inputs to be used for most severe effect
- for instance if the first 4 pairs of inputs are used, not so bad, gets linearly worse as more inputs are used
- so fairly rare use case 

For the moment, will ignore, but leaving as open issue

Marking as a question, since we might want to consider going to just a single input, instead of duplicates

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/function-builder/issues/38, we determined that options (1), once instance of each card, is not acceptable.  

@ariel-phet Which of the other options (if any) do you want me to investigate?

**Comment by ariel-phet** [comment]
I think (5) is the correct decision at the moment. Unassigning but leaving as open known issue.

**Comment by pixelzoom** [comment]
Assigning to me. There should be no unassigned function-builder issues at this late date.

**Comment by pixelzoom** [comment]
Might be able to squeeze some more performance out of Warhol by doing this bit more efficiently (Warhol.js, line 134):

```js
        //TODO performance: may be more efficient to create a canvas with background color, then draw image onto it
        // Put image on an optional background, by changing transparent pixels to the background color
        for ( var i = 0; i < grayscaleData.data.length - 4; i += 4 ) {
          if ( grayscaleData.data[ i + 3 ] === 0 ) {
            FBCanvasUtils.setPixelRGBA( grayscaleData, i, 255, 255, 255, 255 );
          }
        }
```

**Comment by pixelzoom** [comment]
I implemented a more efficient method of setting the background color in Warhol.  Reminder to self that I need to test it on iPad2 with the worst-case scenario of MysteryC + Warhol + Warhol and 2 instances of each card in the output carousel.

**Comment by pixelzoom** [comment]
Version the this issue was reported with:
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.25/function-builder_en.html

Version with the more efficient method of setting background:
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.44/function-builder_en.html

Testing on iPad2, there is very little (if any) perceptible improvement.

**Comment by pixelzoom** [comment]
Of the options enumerated in https://github.com/phetsims/function-builder/issues/36#issuecomment-218569820, we are down to a choice between these two:

> (4) Replace MysteryC with a less expensive function (imo, this function is incomprehensible in the first place, since unlike MysteryA and B, it's not a combination of the other functions)

> (5) Don't worry about it, and assume if the user puts every card in the output carousel, then it's OK if usability is impacted.

@amanda-phet What would you like to do?

**Comment by amanda-phet** [comment]
I don't think the performance is that bad when all outputs are populated. There is a moment where I see that things are changing, but it's not close to long enough for me to start feeling impatient. 

My vote is to go with option (5).

**Comment by pixelzoom** [comment]
I feel the same way - it's not an unreasonable delay, with minimal image on usability.

Closing.
