### ISSUE TITLE
Consider single input for patterns screen (instead of duplicates)

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/function-builder#38]
It seems we should consider using just a single input for the patterns screen

Reasons to go to just a single input:
- will have a noticeable impact on performance (for instance https://github.com/phetsims/function-builder/issues/36)
- more consistent with other screens that do not have duplicate inputs

It seems the main reason for having duplicates was to show that a function always has the same action  on the same input. When using the sim, this learning goal seems fairly clear even with a single input, especially with invertable functions where you can drag the input back and forth through the builder.

Assigning to @amanda-phet for her thoughts if duplicate inputs on the patterns screen are absolutely necessary.

**Comment by pixelzoom** [comment]
Or in the terminology of the sim... Should we have 1 instance of each card instead of 2 instances?

**Comment by amanda-phet** [comment]
I believe two instances of each input are necessary. While it's true that someone could indirectly figure out that a function is consistent with only one, we want to be very explicit here in order to achieve the learning goal.

Get Outlook for Android<https://aka.ms/ghei36>



On Thu, May 12, 2016 at 11:52 AM -0700, "Chris Malley" <notifications@github.com<mailto:notifications@github.com>> wrote:


Or in the terminology of the sim... Should we have 1 instance of each card instead of 2 instances?

-

**Comment by pixelzoom** [comment]
Reducing to 1 instance of each card was one of the performance-improvement options mentioned in https://github.com/phetsims/function-builder/issues/36#issuecomment-218569820.  It sounds like that's not acceptable, so we'll need to consider the other options.

Assigning to @ariel-phet, feel free to close if there's nothing else to do here.

**Comment by ariel-phet** [comment]
Closing
