### ISSUE TITLE
Reconsider having functions cards with pickers be active in the carousel

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/function-builder#48]
When I use the sim on iPad (http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.31/function-builder_en.html) now that the pickers are working and such, I still find the behavior can feel a bit buggy when trying to move the function pieces from the carousel to the builder.

My reasoning is as follows:

1. In the other screens, the user has been "taught" the natural flow of the sim is to put functions in the builder, all other function pieces can be grabbed from there center and it is natural to do so

2. if you grab a function piece (using a touch device) and hit the number picker, your finger is likely obscruing the fact that you have changed a number, therefore you had a desired action (move the function piece) and it has not occurred, and obvious feedback may be unavailable. Thus leading to the buggy feeling.

3. The stated learning goal by @kathy-phet was it might be nice to change function pieces within the carousel to ask a predictive question, but that seems reasonable to facilitate just by using the interactivity when they are actually in the builder or even if not. eg (what do you think will happen when I put a "plus 3" card here?)

@samreid also agreed this behavior felt buggy so I want to bring it back up in design meeting. Assigning to @kathy-phet for comment

**Comment by samreid** [comment]
My suggestion from 5/16/16 email:

Maybe we can have cake and also eat it?

1. if the user taps and releases on the number spinner, it changes the number.
2. if the user presses on the number spinner and drags more than N pixels, it begins a drag.

Sam

**Comment by pixelzoom** [comment]
Comments:

(1) Users probably will initially touch a picker by mistake. But I believe that they will quickly figure out not to do that.  And that seems preferable to forcing the pickers to be usable only under certain conditions ("when in the builder") and making it impossible to set up desired functions independently of the builder. 

(2) If pickers are changeable only in the builder, then you can't set up a function before putting it in builder.  So when you put it in the builder and start changing it, you have to see (and compute) all of the values that you're not interested in, and that may not be at all related to the activity. For example, if the teacher says "What do you think happens if you add 2 to what's in the builder?", you can't set up a "+ 2" function to do that - you must first move whatever "+" function is currently in the carousel to the builder, then change its picker value to 2 in the builder, while experiencing all of the values required to get you to 2.  That seems unnecessarily distracting and possibly detrimental to predictive activities.

(3) Unless we reset functions in the carousel to 1, what's shown in the carousel is whatever you last created in the builder, and you can't change it in the carousel.  And if you reset functions when returned to the carousel, then you make it unnecessarily difficult/confusing to reorder functions, which something involves returning functions to the carousel.

(4) Preliminary interviews in https://github.com/phetsims/tasks/issues/594 indicated no problems with using the pickers. @amyh-phet did you observe any such problems?

**Comment by amyh-phet** [comment]
@pixelzoom @ariel-phet @samreid @kathy-phet 

One student noticed some strange interactions when he touched the picker and tried to move the function, and he commented that something seemed strange.  He realized that he could drag the function when he moved grabbed a different part of the function.  Student was using a mouse to control the sim.  Both students adjusted the pickers on the function both in the carousel and once the function was on the builder.   I do have a screen capture of both interviews and can send clips of interactions if needed.

**Comment by pixelzoom** [comment]
A few other thoughts...

By default, NumberPicker has a touchArea that is slightly dilated horizontally. By eliminating this horizontal dilation, we can somewhat mitigate the problem of accidentally touching the picker when you mean to grab the function.

Disabling pickers in the carousel doesn't eliminate the usability issues noted by @ariel-phet in https://github.com/phetsims/function-builder/issues/48#issue-155577047.  Interacting with functions in the builder has the identical usability problem - that the user needs to learn to touch the picker vs the function background to accomplish different things.  (And the issue is perhaps worse in the builder; when the 'see inside' windows are visible, there is less of the function background visible to grab.)

I don't think @samreid's suggestion (https://github.com/phetsims/function-builder/issues/48#issuecomment-220134891) addresses the concerns raised by @ariel-phet. If anything, it makes matters worse by creating a situation where the user will be both changing the picker and moving the function.

**Comment by samreid** [comment]
> I don't think @samreid's suggestion (#48 (comment)) addresses the concerns raised by @ariel-phet. If anything, it makes matters worse by creating a situation where the user can be both changing the picker and moving the function.

If the user clicks in the picker and starts dragging the function in the same sequence, restore the picker to its initial value.

**Comment by ariel-phet** [comment]
@pixelzoom can you remove this horizontal dilation, and publish a dev version? I can try it out on the iPad then.

**Comment by pixelzoom** [comment]
So the picker changes, then reverts when you start dragging? That sure sounds confusing.

**Comment by samreid** [comment]
Or only have the picker change if no drag was detected within N milliseconds.

**Comment by pixelzoom** [comment]
@ariel-phet Here's a dev version with zero horizontal dilation:
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.34/function-builder_en.html

**Comment by kathy-phet** [comment]
I tested dev.34 on computer and iPad, and I feel it works well. 

In addition to agreeing with all of the reasons Chris mentioned regarding continuing to allow changing the function picker while in the toolbox. I found that during iPad testing, it was actually a nice constraint that you could not put your finger over the number to move out the function. It actually meant that when I was adding a function I was guaranteed to be able to see the value of the function while I added it and that my finger was not covering the number. This seems good to me. 

K

**Comment by ariel-phet** [comment]
dev.34 definitely seems like an improvement, and a reasonable compromise. Closing.
