### ISSUE TITLE
why is it necessary to set initialWidth and initialHeight for Patterns screen icon?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#68]
In https://github.com/phetsims/function-builder/issues/66, I discovered that it was necessary to set the `initialWidth` and `initialHeight` of the scenery.Image in `FBIconFactory.createPatternsScreenIcon`.

In https://github.com/phetsims/function-builder/issues/66#issuecomment-225231906, I asked @jonathanolson why this is necessary, but did not get an answer before he went on leave. I suspect that it has something to do with where this code is called in the startup sequence, and that some scenery initialization may not have occurred yet.  I'd like to document that in the code.

**Comment by jonathanolson** [comment]
Due to the image not having been loaded by the browser yet (the img tag), we can't immediately get a width/height. Since we want to have a proper width/height before the image is used for bounds purposes, it's helpful to specify the initial values.

The following documentation is in Image.js for handling image elements (in the cleanup branch):
```
   * HTMLImageElement - A normal HTML <img>. If it hasn't been fully loaded yet, Scenery will take care of adding a
   *   listener that will update Scenery with its width/height (and load its data) when the image is fully loaded. NOTE
   *   that if you just created the <img>, it probably isn't loaded yet, particularly in Safari. If the Image node is
   *   constructed with an <img> that hasn't fully loaded, it will have a width and height of 0, which may cause issues
   *   if you are using bounds for layout. Please see initialWidth/initialHeight notes below.
```

Is that sufficient?

**Comment by pixelzoom** [comment]
👍 Closing.
