### ISSUE TITLE
Challenge #1 is always the same color

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/function-builder#75]
I know that it is intended for resetting or refreshing, that it will always start on challenge 1 and use the same colors each time. 
But it's also stated in phetsims/tasks#628 that

> • You should never see the same colors used for functions twice in a row. 

If you go through and generate new challenges until you get a repeat of the first one, it will be the same color every time. As far as I can tell, all of the other challenges use different colors each time they are repeated. 
I'm just wondering if this is actually a problem or if it is intended.

**Comment by pixelzoom** [comment]
The current behavior is as desired - the default challenge is always the same, and always uses the same colors. This is so that the teacher has a reproducible challenge for starting activities, etc.

The statement "You should never see the same colors used for functions twice in a row" means that when switching from one challenge to the next, you should never have the same colors for 2 challenges in a row.  If does not mean that the same challenge may at some point be assigned the same colors - though (with the exception of the default challenge) it is highly unlikely.

So, closing as "not an issue".

**Comment by pixelzoom** [comment]
And I should also say... Thank you @brroberts1231 for reporting this. I don't want to discourage this type of report - it's always better to report if there's any question.  My wording in phetsims/tasks#628 was clearly to blame.  I should have said ""You should never see the same colors used *in two consecutive challenges*".
