### ISSUE TITLE
Many positional parameters in some constructors

### ISSUE THREAD

**Issue by andrewadare** [phetsims/function-builder#77]
This is not an explicit code review checklist item. Nor is any action necessarily expected--this is more of a code design question for my information.

Several constructors take a large number of parameters. If I check for functions taking more than 6 parameters by adding `"max-params": [2,6]` to my .eslintrc, I get the following:
```
/Users/adare/phetsims/function-builder/js/common/view/cards/CardNode.js
  33:3  error  This function has too many parameters (8). Maximum allowed is 6  max-params

/Users/adare/phetsims/function-builder/js/common/view/cards/EquationCardNode.js
  32:3  error  This function has too many parameters (7). Maximum allowed is 6  max-params

/Users/adare/phetsims/function-builder/js/common/view/cards/ImageCardNode.js
  31:3  error  This function has too many parameters (7). Maximum allowed is 6  max-params

/Users/adare/phetsims/function-builder/js/common/view/cards/NumberCardNode.js
  32:3  error  This function has too many parameters (7). Maximum allowed is 6  max-params

/Users/adare/phetsims/function-builder/js/common/view/containers/CardContainer.js
  52:18  error  This function has too many parameters (8). Maximum allowed is 6  max-params
```
(Six is an arbitrary limit.) There are two reasons to bring this up:

1. The API becomes more difficult to use and more error-prone. The language provides poor enforcements on type-safety and argument count.
2. If/when the sim is instrumented for PhET-iO, most constructors will receive yet another positional parameter when the tandem instance is added.

I'm aware of how much work it would be to change this now (see https://github.com/phetsims/capacitor-lab-basics/issues/70), but I think this will keep coming up. What is the "best practice" in general for parameter count limits?

**Comment by pixelzoom** [comment]
The cases that you're referring to are all constructors. General guidelines for constructors are:

(1) Everything required to instantiate a valid object must be passed to the constructor. 
(2) Anything that DOES have a reasonable default value is part of the options hash.
(3) Anything that DOES NOT have a reasonable default value is a required parameter.

I'll review the examples that you've pointed out (all of which pertain to cards), but I believe that they follow these guidelines. Unfortunately, the cards in this sim need to know about quite a few things in order to handle the intricacies of dragging, animation and multi-touch.

**Comment by pixelzoom** [comment]
Related to #55 (code review).

**Comment by pixelzoom** [comment]
Here are the offenders.

(1) Card nodes and their containers. 

CardNode is the base type, and its constructor is:

```js
function CardNode( card, contentNode, inputContainer, outputContainer, builderNode, dragLayer, seeInsideProperty, options )
```

Subtypes ImageCardNode, NumberCardNode and EquationCardNode have constructors with identical parameters.

Card "containers" are responsible for creating CardNode subtypes, via this abstract function:

```
CardContainer.createCards: function( numberOfInstances, scene, inputContainer, outputContainer, builderNode, dragLayer, seeInsideLayer, seeInsideProperty )
```

This function is implemented (with identical parameters) by subtype ImageCardContainer, NumberCardContainer and EquationCardContainer.

In all of these cases, parameters `inputContainer, outputContainer, builderNode, dragLayer, seeInsideProperty` are all needed for drag handling and animation.

(2) Function nodes and their containers

FunctionNode is the base type, and its constructor is:

```js
function FunctionNode( functionInstance, container, builderNode, dragLayer, options )
```

Subtypes ImageFunctionNode, MathFunctionNode, EditableMathFunctionNode and MysteryFunctionNode have constructors with identical parameters.

Function "containers" are responsible for creating function FunctionNode subtypes, via this function:

```js
FunctionContainer.createFunctions: function( numberOfInstances, scene, builderNode, dragLayer )
```

In all of these cases, parameters `container, builderNode, dragLayer,` are all needed for drag handling and animation.

**Comment by pixelzoom** [comment]
So back to what I said in https://github.com/phetsims/function-builder/issues/77#issuecomment-229529624... CardNode and FunctionNode encapsulate *everything* related to their drag handling and animation, and the downside to that is that they need to know about all of the things that are involved in drag handling and animation.  The alternative is to distribute responsibility for drag handling and animation - I did investigate that early on, and it turned into quite the mess.   So I think that in this case, it's better to keep this (complicated) functionality encapsulated in one place, and live with the coupling that comes with this many parameters.

Back to @andrewadare.  Let me know if you have other questions or suggestions. Otherwise feel free to close.

**Comment by andrewadare** [comment]
@pixelzoom I agree with your assessment that trying to split the drag handling and animation concerns would not buy much, and is not worth the cost in stability (at this late stage) and in dev time. This has been informative for me, and worth discussing. Closing now.

**Comment by pixelzoom** [comment]
@andrewadare I added this comment to the root cause of the parameter explosion, the CardNode and FunctionNode constructors:

```js
  * NOTE: The relatively large number of constructor parameters here is a tradeoff. There are many things
   * involved in drag handling and animation. I could have reduced the number of parameters by distributing
   * the responsibility for drag handling and animation. But encapsulating all responsibilities here seemed
   * like a superior solution.  So I chose encapsualtion at the expense of some increased coupling.
   * See discussion in https://github.com/phetsims/function-builder/issues/77
```

**Comment by andrewadare** [comment]
:thumbsup:
