### ISSUE TITLE
colorblind testing

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#80]
The master checklist (https://github.com/phetsims/function-builder/issues/2) shows this task as not completed:

- [ ] Mockups checked for colorblind and greyscale 

Has this sim received colorblind testing?

**Comment by pixelzoom** [comment]
Raising priority to "top", since this is a prerequisite for meeting the "final change requests" deadline in https://github.com/phetsims/function-builder/issues/86.

**Comment by ariel-phet** [comment]
I just ran through the live sim in gray-scale

- All looks good (warhol still functions quite nicely)
- cycling through the triple mystery generally shows good color value contrast

The only two minor things I see are:
1. Mystery(A) and Mystery(B) look similar on patterns screen
2. All multiplication functions look similar color value on numbers screen

I do not think either of these is a concern since the labels make these functions clearly different.

**Comment by amanda-phet** [comment]
I looked at color-blindness in the original design and just did a quick check with features that were more recently added and it looks good to me.
