### ISSUE TITLE
Layout bug in equations

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/function-builder#88]
In one interview, a student thought that the "slope-intercept" checkbox was meant to change the appearance of the fraction in the example below. This seems to be a layout bug. 

<img width="619" alt="screen shot 2016-07-07 at 10 00 00 am" src="https://cloud.githubusercontent.com/assets/7852916/16660019/ec5a0a2c-4429-11e6-8695-d649f2948841.png">

<img width="588" alt="screen shot 2016-07-07 at 10 00 05 am" src="https://cloud.githubusercontent.com/assets/7852916/16660027/f4522ffc-4429-11e6-8223-d4df79f7fcf6.png">

**Comment by pixelzoom** [comment]
In case it's difficult to see by comparing screenshots... The vertical spacing in the fraction is different for the 2 equation forms.   There's more space in the "helpful" form.

**Comment by pixelzoom** [comment]
Fixed in the above commit. But I noticed that the options to the 2 equation forms are duplicated in HelpfulEquationNode and SlopeInterceptEquationNode.  We want the options for both equations to be (and to stay!) the same, so I'm going factor out the duplication.

**Comment by pixelzoom** [comment]
@amanda-phet Please verify in this dev version:

http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.70/function-builder_en.html

But note that you'll never see 'y = 2/3' for the helpful form, because of the change request in https://github.com/phetsims/function-builder/issues/87.  It will now be 'y = [0x + 2]/3'.

If everything looks OK, please close this issue.

**Comment by amanda-phet** [comment]
I tried some similar functions and the layout looks consistent to me.

**Comment by pixelzoom** [comment]
Related to #86
