### ISSUE TITLE
Change "slope-intercept" checkbox to "simplified"

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/function-builder#90]
In the 7/5 interviews the students already had knowledge of linear functions and graphing, so seeing the word "slope-intercept" in the equation drawer set them up to be thinking about graphing lines, slope, and y-intercept. They both had issues with the graph not zoomed in enough to see the y-intercept. We designed the graph to be a more "qualitative" representation of the function. Therefore, I think the language of this checkbox is influencing their mindset too much. 

Back when we had this conversation about what to call the checkbox, we determined that "simplified" was equivalent to "slope-intercept," so I would like to use that language instead so that students aren't too focused on the graph.

**Comment by pixelzoom** [comment]
I'm very surprised at this request. "Simplified" is a standard math term and is most definitely *not* slope-intercept form.  And it also implies that the unchecked version is "unsimplified", which it also most definitely is not.

I'll certainly defer to you on this, but I suspect that you'll get some blowback from math educators.  And since this will involve changing a string key, it will be relatively costly to change back later.

**Comment by pixelzoom** [comment]
I'm very surprised at this request. "Simplified" is a very specific standard format, and is most definitely *not* the same as slope-intercept form.  And labeling this check box as such also implies that the unchecked version is "unsimplified", which it also most definitely is not.

I'll certainly defer to you on this, but I suspect that you'll get some blowback from math educators.  And since this will involve changing a string key, it will be relatively costly to change back later.

**Comment by pixelzoom** [comment]
@amanda-phet Instead of labeling the check box "simplified", how would you feel about labeling it "simplify".  This seems more appropriate because to simplify an equation means to put in a form that is simpler than the original, whereas "simplified" is a specific form of equation.

**Comment by pixelzoom** [comment]
Related to #86

**Comment by pixelzoom** [comment]
@amanda-phet Here's a version that labels the check box as 'simplify', let me know if this feels OK.

http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.71/function-builder_en.html

**Comment by amanda-phet** [comment]
I'm glad you suggested "simplify". I think it works really well. Thanks for making this change.
