### ISSUE TITLE
Double Warhol image is wrong

### ISSUE THREAD

**Issue by phet-steele** [phetsims/function-builder#92]
No setup required, just put in two Warhol functions. The image in one of the quadrants is wrong, and only shows a single color. I did not find a combination of functions to remedy this.
![doublewarhol](https://cloud.githubusercontent.com/assets/5863899/16740446/603adaea-475c-11e6-8dc9-5dd26b2bd88b.PNG)

Single Warhol is fine. Seen on Win 10 browsers and OSX 10.11.5 browsers. For phetsims/tasks/issues/638.

Troubleshooting information:
Name: ‪Function Builder‬
URL: http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-rc.1/function-builder_en.html
Version: 1.0.0-rc.1 2016-07-11 16:15:00 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
Language: en-US
Window: 1536x739
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"9a0e2f3a","branch":"master"},"babel":{"sha":"101ec12c","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"9059e93b","branch":"master"},"dot":{"sha":"3628c3ae","branch":"master"},"function-builder":{"sha":"7daf67e1","branch":"1.0"},"joist":{"sha":"94bc734c","branch":"master"},"kite":{"sha":"88f0c3a0","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"scenery":{"sha":"942889ad","branch":"master"},"scenery-phet":{"sha":"0d6b589e","branch":"master"},"sherpa":{"sha":"03590a07","branch":"master"},"sun":{"sha":"cccaf534","branch":"master"},"tandem":{"sha":"a8ac284b","branch":"master"},"twixt":{"sha":"53b31872","branch":"master"}}

**Comment by phet-steele** [comment]
@pixelzoom believes this problem has been around since 1.0.0-dev.18 and is a result of #14. For reference here is first a double Warhol image from dev.17 followed by a double Warhol image from dev.18. Notice the dev.18 image is slightly different than what's being seen in 1.0.0-rc.1,  where the butterflies can still be partially seen. dev.17 completely wipes out the images.

17
![doublewarhol17](https://cloud.githubusercontent.com/assets/5863899/16740715/95c746e8-475d-11e6-90b5-aec7b71a954d.PNG)

18
![doublewarhol18](https://cloud.githubusercontent.com/assets/5863899/16740723/9de28a2c-475d-11e6-8d17-618b80e2b0fa.PNG)

**Comment by pixelzoom** [comment]
This has been the case since 1.0.0-dev.18, when Warhol was reimplemented to address #14. 

Looking at a single Warhol, I can guess what is causing this:

![screenshot_50](https://cloud.githubusercontent.com/assets/3046552/16741053/dd2680de-475e-11e6-89cb-a97adf11de61.png)

When mapped to grayscale, all of the pixels in the lower-right will have intensities in the same "band", and will be therefore mapped to the same color.  The fix for this is to adjust the color map for the lower-left quadrant so that this doesn't happen.

**Comment by pixelzoom** [comment]
To achieve the desired result with both single and double Warhol, it's important that the color maps maintain a high contrast between foreground and background.  That was not the case with the current colormaps, which is why the foreground and background were mapped to the same color when double-Warhol was applied.  

I've tweaked the colormaps, and here's what the butterfly looks like with single Warhol:

![screenshot_51](https://cloud.githubusercontent.com/assets/3046552/16742008/1f5ee794-4763-11e6-8fae-b5507f7845e7.png)

double-Warhol:

![screenshot_52](https://cloud.githubusercontent.com/assets/3046552/16742011/2680d938-4763-11e6-8b33-22a6af0b075f.png)

and on the Patterns screen icon:

![screenshot_54](https://cloud.githubusercontent.com/assets/3046552/16742018/2d85ca22-4763-11e6-970d-d2b7c6d3420f.png)

I checked all cards (using the `?populateOutput` query parameter) and they all look good, no problems with foreground and background merging to form a solid rectangle.  There are some mappings that make quadrants look somewhat similar.  But this is to be expected, and is impossible to prevent in general.

@amanda-phet @ariel-phet @phet-steele Please test drive this dev version with the new colormaps and verify that you're OK with this change.

http://www.colorado.edu/physics/phet/dev/html/function-builder/1.1.0-dev.1/function-builder_en.html

**Comment by pixelzoom** [comment]
Btw... It's the upper-left and lower-right quadrants that look somewhat similar (probably even more so to colorblind people).  If we wanted to correct this, we'd need to totally change the colormap for one of these quadrants.

**Comment by phet-steele** [comment]
Skype with @pixelzoom:
[1:10:48 PM] Steele Dalton: if two quadrants in a Warhol look very similar after applying a grayscale, would that be indicative of a colorblind issue?
[1:13:39 PM] Chris Malley: If you set up Warhol -> Warhol -> Grayscale, then yeah, that will be somewhat similar to what a colorblind person will see.  And you'll definitely see some solid gray rectangles, where the foreground image disappears. No way to address this in general.
[1:14:19 PM] Steele Dalton: well if I tell you it gets way worse in your 1.1.0-dev.1....much more solid gray rectangles
[1:14:33 PM] Steele Dalton: then what would you say?
[1:14:40 PM] Chris Malley: it's a tradeoff.
[1:14:45 PM] Steele Dalton: I see
[1:15:49 PM] Chris Malley: we can continue to play with colormaps until we get something that everyone finds more satisfactory.  but that will likely be a long process.
[1:16:43 PM] Chris Malley: when you say "worse in 1.1.0-dev.1", do you mean worse with double Warhol, or also worse with single?
[1:16:53 PM] Steele Dalton: the prior

1.0.0-rc.1:
![doublewarholgrayrc](https://cloud.githubusercontent.com/assets/5863899/16743572/4f2c892a-476a-11e6-9b3f-78f24c82b6e2.PNG)

1.1.0-dev.1:
![doublewarholgraydev](https://cloud.githubusercontent.com/assets/5863899/16743578/538ce87a-476a-11e6-90d1-ec3235e7ccb8.PNG)

**Comment by pixelzoom** [comment]
Since the point of Warhol is to get an idea of what the function does rather than to critically examine the resulting image, I guess I'm not too concerned about it. But that doesn't mean that others on the team won't want to tweak it some more. 

@amanda-phet @ariel-phet If you want to tweak colormaps further, then I'd recommend that I create a tool that allows you experiment with various colors yourselves. Quickest for me (2-3 hours) but most cumbersome for you would be to specify colors via query parameters. Something more user-friendly (possibly added to the 'Test' screen) would take me 4-6 hours.

**Comment by ariel-phet** [comment]
@pixelzoom I agree the point is to get an "idea of the function" -- the single warhol in the dev version you sent works perfectly (even in grayscale). So if the double has a few rectangles that appear to be a solid block of color I am not too concerned. If someone walks away and can say "that function take the input splits it into four small blocks, and rearranges the color somehow" that is definitely good enough in my opinion.

I say leave where it is. This is a clear case of good being better than perfect.

**Comment by amanda-phet** [comment]
I 100% agree with @ariel-phet 's comment. Let's leave it as it is right now in 1.1.0-dev.1.

**Comment by pixelzoom** [comment]
Ok, leave as is.

I'll leave this assigned to me, so that I include it in regression testing for 1.0.0-rc.2.

**Comment by pixelzoom** [comment]
Please verify in http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-rc.2/function-builder_en.html.

**Comment by phet-steele** [comment]
There is another setup of functions showing a problem (not necessarily Double Warhol) that I believe cannot be addressed, but I will make a note of it. Should not be blocking release:

![twoleftfeet](https://cloud.githubusercontent.com/assets/5863899/16814336/9a79e484-48f2-11e6-8d31-1ccd7ca4e48e.PNG)

**Comment by phet-steele** [comment]
Otherwise, verified on Win 10 Chrome and OSX 10.11.5 Chrome

**Comment by pixelzoom** [comment]
Skype discuss that @phet-steele more succinctly summarized in https://github.com/phetsims/function-builder/issues/92#issuecomment-232439522 (but with less entertainment value :)

> [7/13/16, 11:56:45 AM] Steele Dalton: am I beating a dead horse when I point out other solid color quadrants involving Warhol and other function combinations?
[7/13/16, 11:57:00 AM] Chris Malley: no
[7/13/16, 11:57:15 AM] Chris Malley: are these new, or just not noticed in previous RC?
[7/13/16, 11:57:33 AM] Chris Malley: single or double Warhol?
[7/13/16, 11:58:23 AM] Steele Dalton: they aren't unknown per se, same root problem as in "Double Warhol"
[7/13/16, 11:59:06 AM] Chris Malley: example?
[7/13/16, 11:59:16 AM] Steele Dalton: and in that issue we settled on realizing we cant pick a colormap that satisfies every situation
[7/13/16, 11:59:21 AM] Steele Dalton: sec
[7/13/16, 12:00:21 PM] Chris Malley: yes, we did. but the conclusion in https://github.com/phetsims/function-builder/issues/92#issuecomment-231840247 was that we shouldn't worry about ending up with similar colors, not that we should live with the foreground image disappearing.
[7/13/16, 12:00:22 PM] Steele Dalton: rainbow Warhol grayscale
[7/13/16, 12:00:34 PM] Chris Malley: checking...
[7/13/16, 12:01:55 PM] Chris Malley: Yeah, that's the kind of thing that we can't possibly address.  This is to be expected (and unavoidable) with multiple functions that perform different color mappings.
[7/13/16, 12:02:38 PM] Steele Dalton: so yea...dead horse
[7/13/16, 12:02:38 PM] Chris Malley: But please do note this in https://github.com/phetsims/function-builder/issues/92, just indicate it's not something we can address, and shouldn't preclude closing the issue.
[7/13/16, 12:03:08 PM] Chris Malley: dead butterfly, dead stickman, dead snowflake,...
[7/13/16, 12:03:25 PM] Steele Dalton: (facepalm)
