### ISSUE TITLE
Invisible stick figure

### ISSUE THREAD

**Issue by phet-steele** [phetsims/function-builder#96]
@pixelzoom @amanda-phet if you apply Rainbow -> Warhol to the stick figure man,  you get four empty squares. Is this another issue similar to #92 in that it really just comes down to colormaps and can't be solved in general?

![rainwarhol](https://cloud.githubusercontent.com/assets/5863899/16779654/6f79d84c-4830-11e6-8918-a89adb6c17c2.PNG)

For phetsims/tasks/issues/638.

**Comment by pixelzoom** [comment]
The problem here is that the stick figure is nearly black (RGB=51,51,51).  The "invert RGB" function therefore makes it nearly white.  Running it through Warhol results in it being mapped to the background color.

Options for addressing this:

(1) Change the color of the stick figure to the same color as the feet (which doesn't exhibit this problem). 15-20 minutes.

(2) Play around with the Warhol colormaps some more, and cause a problem for some other icon. 2-? hours.

@amanda-phet your call.

**Comment by pixelzoom** [comment]
The problem here is that the stick figure is a single color, which is nearly black (RGB=51,51,51). The "invert RGB" function therefore makes it nearly white (RGB=204,204,204). Running it through Warhol results in it being mapped to the background color.

Options for addressing this:

(1) Change the color of the stick figure to the same color as the feet (which doesn't exhibit this problem). 15-20 minutes.

(2) Play around with the Warhol colormaps some more, and cause a problem for some other icon. 2-? hours.

(3) Leave it as is.

@amanda-phet your call. My recommendation is (1).

**Comment by pixelzoom** [comment]
The problem here is that the stick figure is a single color, which is nearly black (RGB=51,51,51). The "invert RGB" function therefore makes it nearly white (RGB=204,204,204), the same as the background color (white, RGB=255,255,255). So when running the output of "invert RGB" through Warhol, the stick figure and background are mapped to the same grayscale intensity, and therefore mapped to same color.

Options for addressing this:

(1) Leave it as is. (0 minutes)

(2) Change the color of the stick figure to the same color as the feet, which doesn't exhibit this problem. (15-20 minutes)

(3) Play around with the Warhol colormaps some more, and possibly cause a problem for some other icon. (2-? hours)

@amanda-phet your call. My recommendation is (2).

**Comment by amanda-phet** [comment]
How about a variant on (2). 

Rather than make the stick figure sand-colored, is the problem fixed by making it navy (RGB=27,20,100)?

**Comment by pixelzoom** [comment]
RGB=27,20,100 has the same problem as black. It's inverse is RGB=228,235,155, which maps to the same intensity "band" as the background color (white). 

FYI, the computation for intensity is:

```js
      // Convert RGB (0-255) to intensity (0-255), using the non-linear luma coding scheme employed in video systems
      // (e.g. NTSC, PAL, SECAM).  See https://en.wikipedia.org/wiki/Grayscale or the NTSC CCIR 601 specification.
      var intensity = ( 0.2989 * red ) + ( 0.5870 * blue ) + ( 0.1140 * green );
```

**Comment by pixelzoom** [comment]
Here's a screenshot with RGB=27,20,100 for the stickFigure.png input:

![screenshot_56](https://cloud.githubusercontent.com/assets/3046552/16783681/44fced40-4842-11e6-9f89-7066709d22b8.png)

**Comment by pixelzoom** [comment]
RGB=72,91,191 (see color swatch below) is a bit brighter blue and seems to work fine.

![screenshot_57](https://cloud.githubusercontent.com/assets/3046552/16784170/c1b96cd0-4844-11e6-953a-6d300d01380b.png)

**Comment by amanda-phet** [comment]
Great let's use that blue (72,91,191). 

Thanks Chris.

**Comment by pixelzoom** [comment]
Done, color of stickFigure.png changed to RGB=72,91,191.    Screenshots below showing application of InvertRGB and InvertRGB+Warhol.

![screenshot_58](https://cloud.githubusercontent.com/assets/3046552/16784365/b6c3bfe6-4845-11e6-9b09-83f121fef28d.png)

![screenshot_59](https://cloud.githubusercontent.com/assets/3046552/16784373/ba2cb228-4845-11e6-88ea-a069cdc57c37.png)

**Comment by pixelzoom** [comment]
@amanda-phet Please test drive this version and verify that it looks OK:

http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.74/function-builder_en.html

**Comment by amanda-phet** [comment]
Looks great. Closing this issue.

**Comment by pixelzoom** [comment]
Reopening so that I remember to put this on the verification list for 1.0.0-rc.2.

**Comment by pixelzoom** [comment]
Please verify in http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-rc.2/function-builder_en.html.

**Comment by phet-steele** [comment]
Verified on Win 7 & 10 Chrome, OSX 10.11.5 Chrome, and iPad2 iOS 9.3.3
