### ISSUE TITLE
x-axis range too short on the Mystery screen

### ISSUE THREAD

**Issue by phet-steele** [phetsims/function-builder#97]
@amanda-phet @pixelzoom From the results documented in https://github.com/phetsims/function-builder/issues/72#issuecomment-228162485, I do not think extending the max x range to 8 is enough. A good majority of challenges have the x = 7 point cover the x-axis label, maybe the range should be increased?

![7thpoint](https://cloud.githubusercontent.com/assets/5863899/16780696/00692ee4-4835-11e6-9e3a-60a1b69ab3c2.PNG)

Seen on everything, for phetsims/tasks/issues/638.

Troubleshooting information:
Name: ‪Function Builder‬
URL: http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-rc.1/function-builder_en.html
Version: 1.0.0-rc.1 2016-07-11 16:15:00 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
Language: en-US
Window: 1536x739
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"9a0e2f3a","branch":"master"},"babel":{"sha":"101ec12c","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"9059e93b","branch":"master"},"dot":{"sha":"3628c3ae","branch":"master"},"function-builder":{"sha":"7daf67e1","branch":"1.0"},"joist":{"sha":"94bc734c","branch":"master"},"kite":{"sha":"88f0c3a0","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"scenery":{"sha":"942889ad","branch":"master"},"scenery-phet":{"sha":"0d6b589e","branch":"master"},"sherpa":{"sha":"03590a07","branch":"master"},"sun":{"sha":"cccaf534","branch":"master"},"tandem":{"sha":"a8ac284b","branch":"master"},"twixt":{"sha":"53b31872","branch":"master"}}

**Comment by pixelzoom** [comment]
The x-axis range is currently [-8,8], since the range extends to the edges of the graph.

The occasional (partial) occlusion of 'x' was noted in design meetings, and we concluded the having the axis labels fully visible in all situations was not a requirement.  The sim doesn't start with the axis labels occluded, and the labels are visible in most situations.  One could also argue that the 'x' label is still intelligible in the screenshot that @phet-steele provided.  That said...

Options to address this:

(1) Do nothing.

(2) Increase the x-axis range to [-9,9], at the expense of making the graph even less usable.

(3) Make the x range asymmetrical, e.g. [-7,9]. The origin would no longer be in the geometric center of the graph.

@amanda-phet your call.

**Comment by pixelzoom** [comment]
The user will have seen the graph previously in the Equations screen, where the range of inputs is [-4,6] and 'x' is therefore never occluded.  So I doubt that they will be even consciously aware of (or concerned about) the axis labels in the Mystery screen.  So I am recommending option (1) - do nothing.

**Comment by pixelzoom** [comment]
Also note that option (2) would address occlusion of 'x', but won't address translations of 'x'.   The label is allowed to get about 4.5 units wide before it's scaled. For example, see this screenshot with `?stringTest=MyAxisLabel`:

![screenshot_61](https://cloud.githubusercontent.com/assets/3046552/16784881/289faa6a-4848-11e6-8d13-dea5bd840d72.png)

**Comment by amanda-phet** [comment]
Option (1). 

Occluding the x-axis label is very minor.

**Comment by pixelzoom** [comment]
Thanks @amanda-phet. Closing as "won't fix".
